app: serverless-kpi
service: serverless-kpi
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  login:
    handler: src/employee/employee_controller.login
    events:
      - httpApi:
          path: /login
          method: post

  user-headcount:
    handler: src/employee/employee_controller.headcountController
    timeout: 45
    events:
      - httpApi:
          path: /role
          method: post
          
  user-create:
    handler: src/employee/employee_controller.create
    timeout: 45
    events:
      - httpApi:
          path: /employees
          method: post

plugins:
  - serverless-offline
  - serverless-mocha-plugin
